"""Internal Agent Console shell and API explorer."""

from __future__ import annotations

import json
from typing import Any, Literal

import httpx
from fastapi import APIRouter, FastAPI, HTTPException, Request
from fastapi.responses import HTMLResponse, Response
from pydantic import BaseModel, Field


class ConsoleProxyRequest(BaseModel):
    """Proxy request generated by the console API explorer."""

    method: Literal["GET", "POST", "PUT", "PATCH", "DELETE"]
    path: str = Field(..., min_length=1)
    headers: dict[str, str] = Field(default_factory=dict)
    query: dict[str, str | list[str]] = Field(default_factory=dict)
    body: Any = None


def install_agent_console(app: FastAPI) -> None:
    """Mount the Agent Console routes on the FastAPI app."""

    router = APIRouter(include_in_schema=False)

    @router.get("/console", response_class=HTMLResponse)
    async def console_shell() -> HTMLResponse:
        return HTMLResponse(_console_html())

    @router.get("/console/openapi-client.js")
    async def console_openapi_client(request: Request) -> Response:
        openapi = request.app.openapi()
        operations = _openapi_operations(openapi)
        script = _openapi_client_script(operations)
        return Response(script, media_type="application/javascript; charset=utf-8")

    @router.post("/console/api/proxy")
    async def console_proxy(payload: ConsoleProxyRequest, request: Request) -> Response:
        path = _clean_proxy_path(payload.path)
        headers = _proxy_headers(payload.headers, request)
        query_params = _query_param_pairs(payload.query)
        transport = httpx.ASGITransport(app=request.app)

        async with httpx.AsyncClient(
            transport=transport,
            base_url=str(request.base_url).rstrip("/"),
        ) as client:
            proxied = await client.request(
                payload.method,
                path,
                params=query_params,
                headers=headers,
                json=payload.body if payload.body is not None else None,
            )

        response_headers = {}
        if request_id := proxied.headers.get("x-request-id"):
            response_headers["x-request-id"] = request_id
        return Response(
            content=proxied.content,
            status_code=proxied.status_code,
            headers=response_headers,
            media_type=proxied.headers.get("content-type", "application/json"),
        )

    app.include_router(router)


def _clean_proxy_path(path: str) -> str:
    path = path.strip()
    if "://" in path or path.startswith("//"):
        raise HTTPException(status_code=400, detail="Proxy path must be app-relative")
    if not path.startswith("/"):
        path = f"/{path}"
    if path.startswith("/console/api/proxy"):
        raise HTTPException(status_code=400, detail="Proxy recursion is not allowed")
    return path


def _proxy_headers(headers: dict[str, str], request: Request) -> dict[str, str]:
    allowed = {"accept", "content-type", "x-api-key"}
    proxied = {
        key: value
        for key, value in headers.items()
        if key.lower() in allowed and "\n" not in key and "\n" not in value
    }
    if "x-api-key" not in {key.lower() for key in proxied}:
        api_key = request.headers.get("x-api-key")
        if api_key:
            proxied["x-api-key"] = api_key
    return proxied


def _query_param_pairs(query: dict[str, str | list[str]]) -> list[tuple[str, str]]:
    pairs: list[tuple[str, str]] = []
    for key, value in query.items():
        values = value if isinstance(value, list) else [value]
        pairs.extend((key, item) for item in values)
    return pairs


def _openapi_operations(openapi: dict[str, Any]) -> list[dict[str, Any]]:
    operations: list[dict[str, Any]] = []
    for path, path_item in sorted(openapi.get("paths", {}).items()):
        for method, operation in sorted(path_item.items()):
            if method.upper() not in {"GET", "POST", "PUT", "PATCH", "DELETE"}:
                continue
            operations.append(
                {
                    "method": method.upper(),
                    "path": path,
                    "operationId": operation.get("operationId"),
                    "summary": operation.get("summary") or operation.get("operationId") or path,
                    "tags": operation.get("tags", []),
                    "parameters": operation.get("parameters", []),
                    "requestBody": operation.get("requestBody"),
                }
            )
    return operations


def _openapi_client_script(operations: list[dict[str, Any]]) -> str:
    operations_json = json.dumps(operations, separators=(",", ":"))
    return f"""
window.agentConsoleOpenApi = {{ operations: {operations_json} }};
window.agentConsoleClient = {{
  async request({{ method, path, headers = {{}}, query = {{}}, body = null }}) {{
    const response = await fetch('/console/api/proxy', {{
      method: 'POST',
      headers: {{ 'content-type': 'application/json' }},
      body: JSON.stringify({{ method, path, headers, query, body }}),
    }});
    const contentType = response.headers.get('content-type') || '';
    const text = await response.text();
    let data = text;
    if (contentType.includes('application/json') && text) {{
      try {{ data = JSON.parse(text); }} catch (error) {{ data = text; }}
    }}
    return {{ ok: response.ok, status: response.status, headers: contentType, data }};
  }},
}};
""".strip()


def _console_html() -> str:
    return """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Ad Seller Agent Console</title>
  <style>
    :root { color-scheme: light; --ink: #18212f; --muted: #5d6878; --line: #d9dee8;
      --panel: #f7f8fb; --accent: #0f766e; --accent-strong: #0b5f59; --danger: #b42318; }
    * { box-sizing: border-box; }
    body { margin: 0; font-family: Inter, ui-sans-serif, system-ui, -apple-system, sans-serif;
      color: var(--ink); background: #ffffff; }
    header { display: flex; align-items: center; justify-content: space-between; gap: 24px;
      padding: 18px 28px; border-bottom: 1px solid var(--line); background: #ffffff;
      position: sticky; top: 0; z-index: 10; }
    h1 { font-size: 22px; line-height: 1.2; margin: 0; letter-spacing: 0; }
    nav { display: flex; gap: 8px; flex-wrap: wrap; }
    nav a, button { border: 1px solid var(--line); background: #ffffff;
      color: var(--ink); border-radius: 6px; padding: 8px 10px; font: inherit;
      cursor: pointer; text-decoration: none; }
    nav a:hover, button:hover { border-color: var(--accent); color: var(--accent-strong); }
    main { display: grid; grid-template-columns: minmax(260px, 360px) minmax(0, 1fr);
      min-height: calc(100vh - 67px); }
    aside { border-right: 1px solid var(--line); background: var(--panel); padding: 20px;
      overflow: auto; }
    section { padding: 20px 24px; min-width: 0; }
    .toolbar { display: flex; gap: 10px; align-items: center; margin: 0 0 16px; flex-wrap: wrap; }
    input, textarea, select { width: 100%; border: 1px solid var(--line); border-radius: 6px;
      padding: 9px 10px; font: inherit; background: #ffffff; color: var(--ink); }
    textarea { min-height: 140px; resize: vertical;
      font-family: ui-monospace, SFMono-Regular, monospace; }
    .health { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 10px; }
    .metric, .operation { border: 1px solid var(--line); background: #ffffff;
      border-radius: 8px; padding: 12px; }
    .metric b { display: block; font-size: 13px; color: var(--muted); margin-bottom: 6px; }
    .metric span { font-size: 20px; font-weight: 700; overflow-wrap: anywhere; }
    .operation { width: 100%; text-align: left; margin-bottom: 8px; }
    .operation strong { display: block; font-size: 13px; margin-bottom: 4px; }
    .operation span { color: var(--muted); font-size: 13px; overflow-wrap: anywhere; }
    .selected { border-color: var(--accent); box-shadow: inset 3px 0 0 var(--accent); }
    .grid { display: grid; grid-template-columns: 160px minmax(0, 1fr); gap: 12px;
      align-items: start; }
    .response { border: 1px solid var(--line); border-radius: 8px; padding: 14px;
      background: #101827; color: #f6f8fb; overflow: auto; min-height: 220px;
      font: 13px/1.5 ui-monospace, SFMono-Regular, monospace; white-space: pre-wrap; }
    .error { color: var(--danger); }
    @media (max-width: 820px) { header, main { display: block; } aside { border-right: 0;
      border-bottom: 1px solid var(--line); } .health, .grid { grid-template-columns: 1fr; } }
  </style>
</head>
<body>
  <header>
    <h1>Ad Seller Agent Console</h1>
    <nav aria-label="Console navigation">
      <a href="/docs" target="_blank" rel="noreferrer">Swagger</a>
      <a href="/redoc" target="_blank" rel="noreferrer">ReDoc</a>
      <a href="/openapi.json" target="_blank" rel="noreferrer">OpenAPI</a>
      <a href="/mcp" target="_blank" rel="noreferrer">MCP</a>
    </nav>
  </header>
  <main>
    <aside>
      <div class="toolbar">
        <input id="search" type="search" placeholder="Filter operations">
      </div>
      <div id="operations"></div>
    </aside>
    <section>
      <div class="health" aria-label="Health dashboard">
        <div class="metric"><b>API</b><span id="api-health">checking</span></div>
        <div class="metric"><b>Operations</b><span id="operation-count">0</span></div>
        <div class="metric"><b>Selected</b><span id="selected-operation">none</span></div>
      </div>
      <h2 id="operation-title">API Explorer</h2>
      <div class="grid">
        <label for="method">Method</label><select id="method"></select>
        <label for="path">Path</label><input id="path" value="/health">
        <label for="api-key">API Key</label><input id="api-key" type="password" autocomplete="off">
        <label for="body">JSON Body</label><textarea id="body" spellcheck="false"></textarea>
      </div>
      <div class="toolbar">
        <button id="send">Send request</button>
        <button id="health-refresh">Refresh health</button>
      </div>
      <pre id="response" class="response">Select an operation or send /health.</pre>
    </section>
  </main>
  <script src="/console/openapi-client.js"></script>
  <script>
    const methods = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'];
    const method = document.querySelector('#method');
    const path = document.querySelector('#path');
    const apiKey = document.querySelector('#api-key');
    const body = document.querySelector('#body');
    const response = document.querySelector('#response');
    const operations = document.querySelector('#operations');
    const search = document.querySelector('#search');
    methods.forEach((name) => method.append(new Option(name, name)));

    function renderOperations() {
      const filter = search.value.toLowerCase();
      operations.replaceChildren();
      const items = window.agentConsoleOpenApi.operations.filter((operation) => {
        const searchable = `${operation.method} ${operation.path} ${operation.summary}`;
        return searchable.toLowerCase().includes(filter);
      });
      document.querySelector('#operation-count').textContent = String(items.length);
      for (const operation of items) {
        const button = document.createElement('button');
        button.className = 'operation';
        button.innerHTML = `<strong>${operation.method} ${operation.path}</strong>` +
          `<span>${operation.summary}</span>`;
        button.addEventListener('click', () => selectOperation(operation, button));
        operations.append(button);
      }
    }

    function selectOperation(operation, button) {
      document.querySelectorAll('.operation').forEach((item) => item.classList.remove('selected'));
      button.classList.add('selected');
      method.value = operation.method;
      path.value = operation.path;
      document.querySelector('#selected-operation').textContent =
        operation.operationId || operation.path;
      document.querySelector('#operation-title').textContent = operation.summary;
      body.value = operation.requestBody ? '{\\n  \\n}' : '';
    }

    async function sendRequest(targetPath = path.value) {
      let payloadBody = null;
      if (body.value.trim()) {
        try { payloadBody = JSON.parse(body.value); }
        catch (error) {
          response.textContent = `Invalid JSON body: ${error.message}`;
          response.classList.add('error');
          return;
        }
      }
      response.classList.remove('error');
      response.textContent = 'Loading...';
      const headers = {};
      if (apiKey.value) headers['x-api-key'] = apiKey.value;
      const result = await window.agentConsoleClient.request({
        method: method.value,
        path: targetPath,
        headers,
        body: payloadBody,
      });
      response.textContent = JSON.stringify(result, null, 2);
      return result;
    }

    async function refreshHealth() {
      const previousMethod = method.value;
      method.value = 'GET';
      const result = await sendRequest('/health');
      method.value = previousMethod;
      document.querySelector('#api-health').textContent =
        result && result.ok ? 'healthy' : 'check failed';
    }

    document.querySelector('#send').addEventListener('click', () => sendRequest());
    document.querySelector('#health-refresh').addEventListener('click', () => refreshHealth());
    search.addEventListener('input', renderOperations);
    renderOperations();
    refreshHealth();
  </script>
</body>
</html>"""
