#!/usr/bin/env python3
"""Auto-generate reference inventories from the code (EP-9.1 drift guard).

Introspects the *code* — not hand-maintained prose — to emit deterministic
inventory documents that are the authoritative source of truth for:

  * docs/reference/mcp-tools.md    — MCP tools from the FastMCP registry
  * docs/reference/endpoints.md    — REST routes on the FastAPI app
  * docs/reference/event-types.md  — members of the EventType enum

Output is fully sorted / deterministic. The committed files are asserted
byte-for-byte against fresh output by
``tests/unit/test_docs_inventory_drift.py``, so any code change that adds or
removes a tool / endpoint / event fails CI until the docs are regenerated:

    python scripts/generate_inventories.py

Run with ``--check`` to verify (non-zero exit on drift) without writing.
"""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
# Make ``ad_seller`` importable when run as a plain script.
sys.path.insert(0, str(REPO_ROOT / "src"))

DOCS_DIR = REPO_ROOT / "docs" / "reference"

_BANNER = (
    "<!-- AUTO-GENERATED by scripts/generate_inventories.py — DO NOT EDIT BY HAND. -->\n"
    "<!-- Regenerate with: python scripts/generate_inventories.py -->\n"
)


def _first_line(text: str | None) -> str:
    """Return the first non-empty line of ``text``, collapsed to one line."""
    if not text:
        return ""
    for line in text.splitlines():
        stripped = line.strip()
        if stripped:
            return stripped
    return ""


def _md_escape(text: str) -> str:
    """Escape pipe characters so table cells stay well-formed."""
    return text.replace("|", "\\|")


def generate_mcp_tools() -> str:
    """Enumerate registered MCP tools from the FastMCP registry."""
    from ad_seller.interfaces.mcp_server import mcp

    tools = asyncio.run(mcp.list_tools())
    rows = sorted(tools, key=lambda t: t.name)

    lines = [
        _BANNER,
        "# MCP Tools",
        "",
        "Tools exposed by the seller MCP server (`ad_seller.interfaces.mcp_server`),",
        "enumerated from the live FastMCP registry.",
        "",
        f"**Total: {len(rows)} tools**",
        "",
        "| Tool | Description |",
        "| --- | --- |",
    ]
    for tool in rows:
        desc = _md_escape(_first_line(getattr(tool, "description", "")))
        lines.append(f"| `{tool.name}` | {desc} |")
    lines.append("")
    return "\n".join(lines)


def generate_endpoints() -> str:
    """Walk the FastAPI app and enumerate its REST routes."""
    from fastapi.routing import APIRoute

    from ad_seller.interfaces.api.main import app

    seen: dict[tuple[str, str], str] = {}
    for route in app.routes:
        if not isinstance(route, APIRoute):
            continue
        methods = sorted(m for m in route.methods if m not in {"HEAD", "OPTIONS"})
        for method in methods:
            seen[(method, route.path)] = route.name or ""

    rows = sorted(seen.items(), key=lambda kv: (kv[0][1], kv[0][0]))

    lines = [
        _BANNER,
        "# REST Endpoints",
        "",
        "Routes registered on the FastAPI application",
        "(`ad_seller.interfaces.api.main:app`), enumerated from the router table.",
        "",
        f"**Total: {len(rows)} endpoints**",
        "",
        "| Method | Path | Handler |",
        "| --- | --- | --- |",
    ]
    for (method, path), name in rows:
        lines.append(f"| `{method}` | `{path}` | `{name}` |")
    lines.append("")
    return "\n".join(lines)


def generate_event_types() -> str:
    """Enumerate the EventType enum members."""
    from ad_seller.events.models import EventType

    rows = sorted(EventType, key=lambda e: e.name)

    lines = [
        _BANNER,
        "# Event Types",
        "",
        "Members of `ad_seller.events.models.EventType`, the canonical set of",
        "event types published on the event bus.",
        "",
        f"**Total: {len(rows)} event types**",
        "",
        "| Name | Value |",
        "| --- | --- |",
    ]
    for member in rows:
        lines.append(f"| `{member.name}` | `{member.value}` |")
    lines.append("")
    return "\n".join(lines)


# (output filename -> generator) — the single source of truth for both the
# writer below and the drift-guard test.
INVENTORIES: dict[str, callable] = {
    "mcp-tools.md": generate_mcp_tools,
    "endpoints.md": generate_endpoints,
    "event-types.md": generate_event_types,
}


def render_all() -> dict[str, str]:
    """Return ``{filename: content}`` for every inventory."""
    return {name: gen() for name, gen in INVENTORIES.items()}


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    check_only = "--check" in argv

    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    drift = []
    for name, content in render_all().items():
        path = DOCS_DIR / name
        current = path.read_text() if path.exists() else None
        if check_only:
            if current != content:
                drift.append(name)
        else:
            path.write_text(content)
            print(f"wrote {path.relative_to(REPO_ROOT)}")

    if check_only:
        if drift:
            print("DRIFT detected in: " + ", ".join(drift), file=sys.stderr)
            print("Run: python scripts/generate_inventories.py", file=sys.stderr)
            return 1
        print("inventories up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
